apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd-image:latest
          ports:
            - containerPort: 80
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: LoadBalancer  
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: httpd

